§server:
  port: 8083
spring:
  # ===============================
  # = Hibernate datasource
  # ===============================
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pizza
    username: postgres
    password: postgres
  # ===============================
  # = JPA configurations
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# ===============================
# = JWT configurations
# ===============================
jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keylength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 3600
  issuer: proselyte